export enum ErrorsType {
  CONNECTION = "CONNECTION",
  SERVER = "SERVER",
  GENERIC_ERROR = "GENERIC_ERROR",
  AUTH_ERROR = "AUTH_ERROR",
  INVALID_DATA = "INVALID_DATA",
  TIMEOUT = "TIMEOUT",
  INVALID_CARD = "INVALID_CARD",
  CANCELLED_BY_USER = "CANCELLED_BY_USER",
  EXCESSIVE_AMOUNT = "EXCESSIVE_AMOUNT",
}
