export enum MixpanelEventsId {
  CHK_PAYMENT_NOTICE_DATA_ENTRY = "CHK_PAYMENT_NOTICE_DATA_ENTRY",
  CHK_PAYMENT_NOTICE_QRCODE_SCAN = "CHK_PAYMENT_NOTICE_QRCODE_SCAN",
  CHK_PAYMENT_NOTICE_DATA_ENTRY_MANUAL = "CHK_PAYMENT_NOTICE_DATA_ENTRY_MANUAL",
  CHK_QRCODE_SCAN_SCREEN_MANUAL_ENTRY = "CHK_QRCODE_SCAN_SCREEN_MANUAL_ENTRY",
  CHK_QRCODE_SCAN_SCREEN = "CHK_QRCODE_SCAN_SCREEN",
  CHK_PAYMENT_NOTICE_MANUAL_ENTRY = "CHK_PAYMENT_NOTICE_MANUAL_ENTRY",
}

export enum MixpanelEventCategory {
  UX = "UX",
}

export enum MixpanelEventType {
  SCREEN_VIEW = "screen view",
  ACTION = "action",
}

export enum MixpanelDataEntryType {
  QR_CODE = "qr_code",
  MANUAL = "manual",
}
