/*

import * as t from "io-ts";

export const CHK_PAYMENT_NOTICE_DATA_ENTRY = t.literal(
  "CHK_PAYMENT_NOTICE_DATA_ENTRY"
);
export type CHK_PAYMENT_NOTICE_DATA_ENTRY = t.TypeOf<
  typeof CHK_PAYMENT_NOTICE_DATA_ENTRY
>;

export const CHK_PAYMENT_NOTICE_QRCODE_SCAN = t.literal(
  "CHK_PAYMENT_NOTICE_QRCODE_SCAN"
);
export type CHK_PAYMENT_NOTICE_QRCODE_SCAN = t.TypeOf<
  typeof CHK_PAYMENT_NOTICE_QRCODE_SCAN
>;

export const CHK_PAYMENT_NOTICE_DATA_ENTRY_MANUAL = t.literal(
  "CHK_PAYMENT_NOTICE_DATA_ENTRY_MANUAL"
);
export type CHK_PAYMENT_NOTICE_DATA_ENTRY_MANUAL = t.TypeOf<
  typeof CHK_PAYMENT_NOTICE_DATA_ENTRY_MANUAL
>;

export const CHK_QRCODE_SCAN_SCREEN_MANUAL_ENTRY = t.literal(
  "CHK_QRCODE_SCAN_SCREEN_MANUAL_ENTRY"
);
export type CHK_QRCODE_SCAN_SCREEN_MANUAL_ENTRY = t.TypeOf<
  typeof CHK_QRCODE_SCAN_SCREEN_MANUAL_ENTRY
>;

export const CHK_QRCODE_SCAN_SCREEN = t.literal("CHK_QRCODE_SCAN_SCREEN");
export type CHK_QRCODE_SCAN_SCREEN = t.TypeOf<typeof CHK_QRCODE_SCAN_SCREEN>;

export const CHK_PAYMENT_NOTICE_MANUAL_ENTRY = t.literal(
  "CHK_PAYMENT_NOTICE_MANUAL_ENTRY"
);
export type CHK_PAYMENT_NOTICE_MANUAL_ENTRY = t.TypeOf<
  typeof CHK_PAYMENT_NOTICE_MANUAL_ENTRY
>;

*/

export enum MixpanelEventsId {
  CHK_PAYMENT_NOTICE_DATA_ENTRY = "CHK_PAYMENT_NOTICE_DATA_ENTRY",
  CHK_PAYMENT_NOTICE_QRCODE_SCAN = "CHK_PAYMENT_NOTICE_QRCODE_SCAN",
  CHK_PAYMENT_NOTICE_DATA_ENTRY_MANUAL = "CHK_PAYMENT_NOTICE_DATA_ENTRY_MANUAL",
  CHK_QRCODE_SCAN_SCREEN_MANUAL_ENTRY = "CHK_QRCODE_SCAN_SCREEN_MANUAL_ENTRY",
  CHK_QRCODE_SCAN_SCREEN = "CHK_QRCODE_SCAN_SCREEN",
  CHK_PAYMENT_NOTICE_MANUAL_ENTRY = "CHK_PAYMENT_NOTICE_MANUAL_ENTRY",
}
