import { acceptCookiePolicy, selectLanguage } from "./utils/helpers";

const language = "it";

describe("Unauthorized npg final status mapping tests", () => {

  /**
     * Test input and configuration
  */

  const CHECKOUT_OUTCOME_URL = `http://localhost:1234/esito?lng=${language}`;

  /**
   * Add all mock flow. Reference to the flow defined into the checkout be mock
   */

  const mockFlowWithExpectedResultMap = new Map([
    [
      "AUTHORIZATION_REQUESTED_NO_NPG_OUTCOME",
      { title: "AUTHORIZATION REQUESTED WITH NO NPG OUTCOME", esito: "Attendi la conferma del pagamento" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_EXECUTED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS EXECUTED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_AUTHORIZED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS AUTHORIZED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_PENDING",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS PENDING", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_VOIDED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS VOIDED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_REFUNDED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUSREFUNDED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_FAILED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS FAILED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_CANCELED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS CANCELED", esito: "L’operazione è stata annullata" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DENIED_BY_RISK",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DENIED_BY_RISK", esito: "Autorizzazione negata" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_THREEDS_VALIDATED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS THREEDS_VALIDATED", esito: "Autorizzazione negata" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_THREEDS_FAILED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS THREEDS_FAILED", esito: "Autorizzazione negata" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_100",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 100", esito: "Autorizzazione negata" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_101",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 101", esito: "Il metodo di pagamento è scaduto o non più valido" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_102",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 102", esito: "Autorizzazione negata" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_104",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 104", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_106",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 106", esito: "Autorizzazione negata" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_109",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 109", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_110",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 110", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_111",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 111", esito: "Il metodo di pagamento è scaduto o non più valido" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_115",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 115", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_116",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 116", esito: "Autorizzazione negata" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_117",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 117", esito: "Autorizzazione negata" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_118",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 118", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_119",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 119", esito: "Autorizzazione negata" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_120",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 120", esito: "Autorizzazione negata" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_121",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 121", esito: "Autorizzazione negata" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_122",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 122", esito: "Autorizzazione negata" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_123",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 123", esito: "Autorizzazione negata" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_124",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 124", esito: "Autorizzazione negata" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_125",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 125", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_126",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 126", esito: "Autorizzazione negata" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_129",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 129", esito: "Autorizzazione negata" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_200",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 200", esito: "Autorizzazione negata" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_202",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 202", esito: "Autorizzazione negata" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_204",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 204", esito: "Autorizzazione negata" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_208",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 208", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_209",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 209", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_210",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 210", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_413",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 413", esito: "Autorizzazione negata" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_888",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 888", esito: "Autorizzazione negata" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_902",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 902", esito: "Autorizzazione negata" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_903",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 903", esito: "Autorizzazione negata" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_904",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 904", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_906",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 906", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_907",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 907", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_908",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 908", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_909",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 909", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_911",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 911", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_913",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 913", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_999",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 999", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_GENERIC",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND GENERIC ERROR CODE", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_EXECUTED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS EXECUTED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_AUTHORIZED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS AUTHORIZED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_PENDING",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS PENDING", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_VOIDED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS VOIDED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_REFUNDED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUSREFUNDED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_FAILED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS FAILED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_CANCELED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS CANCELED", esito: "L’operazione è stata annullata" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DENIED_BY_RISK",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DENIED_BY_RISK", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_THREEDS_VALIDATED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS THREEDS_VALIDATED", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_THREEDS_FAILED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS THREEDS_FAILED", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_100",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 100", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_101",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 101", esito: "Il metodo di pagamento è scaduto o non più valido" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_102",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 102", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_104",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 104", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_106",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 106", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_109",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 109", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_110",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 110", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_111",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 111", esito: "Il metodo di pagamento è scaduto o non più valido" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_115",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 115", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_116",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 116", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_117",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 117", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_118",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 118", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_119",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 119", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_120",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 120", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_121",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 121", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_122",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 122", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_123",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 123", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_124",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 124", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_125",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 125", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_126",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 126", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_129",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 129", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_200",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 200", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_202",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 202", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_204",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 204", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_208",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 208", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_209",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 209", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_210",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 210", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_413",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 413", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_888",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 888", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_902",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 902", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_903",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 903", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_904",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 904", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_906",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 906", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_907",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 907", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_908",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 908", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_909",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 909", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_911",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 911", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_913",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 913", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_999",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 999", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_GENERIC",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND GENERIC ERROR CODE", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_EXECUTED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS EXECUTED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_AUTHORIZED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS AUTHORIZED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_PENDING",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS PENDING", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_VOIDED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS VOIDED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_REFUNDED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUSREFUNDED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_FAILED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS FAILED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_CANCELED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS CANCELED", esito: "L’operazione è stata annullata" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DENIED_BY_RISK",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DENIED_BY_RISK", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_THREEDS_VALIDATED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS THREEDS_VALIDATED", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_THREEDS_FAILED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS THREEDS_FAILED", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_100",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 100", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_101",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 101", esito: "Il metodo di pagamento è scaduto o non più valido" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_102",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 102", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_104",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 104", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_106",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 106", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_109",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 109", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_110",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 110", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_111",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 111", esito: "Il metodo di pagamento è scaduto o non più valido" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_115",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 115", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_116",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 116", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_117",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 117", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_118",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 118", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_119",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 119", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_120",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 120", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_121",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 121", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_122",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 122", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_123",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 123", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_124",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 124", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_125",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 125", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_126",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 126", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_129",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 129", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_200",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 200", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_202",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 202", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_204",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 204", esito: "Autorizzazione negata" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_208",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 208", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_209",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 209", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_210",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 210", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_413",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 413", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_888",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 888", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_902",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 902", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_903",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 903", esito: "Autorizzazione negata" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_904",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 904", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_906",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 906", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_907",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 907", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_908",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 908", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_909",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 909", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_911",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 911", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_913",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 913", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_999",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 999", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_GENERIC",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND GENERIC ERROR CODE", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "CLOSED_WITH_NPG_AUTH_STATUS_EXECUTED_SEND_PAYMENT_RESULT_NOT_RECEIVED",
      { title: "CLOSED WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT NOT_RECEIVED", esito: "Attendi la conferma del pagamento" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_AUTHORIZED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS AUTHORIZED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_PENDING",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS PENDING", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_VOIDED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS VOIDED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_REFUNDED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUSREFUNDED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_FAILED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS FAILED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_CANCELED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS CANCELED", esito: "L’operazione è stata annullata" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DENIED_BY_RISK",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DENIED_BY_RISK", esito: "Autorizzazione negata" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_THREEDS_VALIDATED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS THREEDS_VALIDATED", esito: "Autorizzazione negata" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_THREEDS_FAILED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS THREEDS_FAILED", esito: "Autorizzazione negata" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_100",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 100", esito: "Autorizzazione negata" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_101",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 101", esito: "Il metodo di pagamento è scaduto o non più valido" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_102",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 102", esito: "Autorizzazione negata" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_104",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 104", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_106",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 106", esito: "Autorizzazione negata" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_109",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 109", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_110",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 110", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_111",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 111", esito: "Il metodo di pagamento è scaduto o non più valido" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_115",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 115", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_116",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 116", esito: "Autorizzazione negata" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_117",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 117", esito: "Autorizzazione negata" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_118",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 118", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_119",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 119", esito: "Autorizzazione negata" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_120",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 120", esito: "Autorizzazione negata" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_121",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 121", esito: "Autorizzazione negata" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_122",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 122", esito: "Autorizzazione negata" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_123",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 123", esito: "Autorizzazione negata" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_124",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 124", esito: "Autorizzazione negata" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_125",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 125", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_126",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 126", esito: "Autorizzazione negata" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_129",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 129", esito: "Autorizzazione negata" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_200",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 200", esito: "Autorizzazione negata" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_202",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 202", esito: "Autorizzazione negata" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_204",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 204", esito: "Autorizzazione negata" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_208",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 208", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_209",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 209", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_210",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 210", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_413",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 413", esito: "Autorizzazione negata" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_888",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 888", esito: "Autorizzazione negata" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_902",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 902", esito: "Autorizzazione negata" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_903",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 903", esito: "Autorizzazione negata" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_904",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 904", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_906",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 906", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_907",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 907", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_908",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 908", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_909",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 909", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_911",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 911", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_913",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 913", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_999",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 999", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_GENERIC",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND GENERIC ERROR CODE", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "NOTIFICATION_REQUESTED_WITH_NPG_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_OK",
      { title: "NOTIFICATION REQUESTED WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT OK", esito: "Hai pagato" }
    ],
    [
      "NOTIFICATION_REQUESTED_WITH_NPG_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_KO",
      { title: "NOTIFICATION REQUESTED WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT KO", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "NOTIFICATION_ERROR_WITH_NPG_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_OK",
      { title: "NOTIFICATION ERROR WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT OK", esito: "Hai pagato" }
    ],
    [
      "NOTIFICATION_ERROR_WITH_NPG_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_KO",
      { title: "NOTIFICATION ERROR WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT KO", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "NOTIFIED_OK_WITH_NPG_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_OK",
      { title: "NOTIFIED OK WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT OK", esito: "Hai pagato" }
    ],
    [
      "NOTIFIED_KO_WITH_NPG_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_KO",
      { title: "NOTIFIED KO ERROR WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT KO", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_REQUESTED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION_REQUESTED TRANSACTION", esito: "Si è verificato un errore imprevisto" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_EXECUTED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_AUTHORIZED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS AUTHORIZED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_PENDING",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS PENDING", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_VOIDED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS VOIDED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_REFUNDED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUSREFUNDED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_FAILED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS FAILED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_CANCELED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS CANCELED", esito: "L’operazione è stata annullata" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DENIED_BY_RISK",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DENIED_BY_RISK", esito: "Autorizzazione negata" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_THREEDS_VALIDATED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS THREEDS_VALIDATED", esito: "Autorizzazione negata" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_THREEDS_FAILED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS THREEDS_FAILED", esito: "Autorizzazione negata" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_100",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 100", esito: "Autorizzazione negata" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_101",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 101", esito: "Il metodo di pagamento è scaduto o non più valido" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_102",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 102", esito: "Autorizzazione negata" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_104",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 104", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_106",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 106", esito: "Autorizzazione negata" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_109",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 109", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_110",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 110", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_111",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 111", esito: "Il metodo di pagamento è scaduto o non più valido" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_115",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 115", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_116",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 116", esito: "Autorizzazione negata" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_117",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 117", esito: "Autorizzazione negata" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_118",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 118", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_119",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 119", esito: "Autorizzazione negata" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_120",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 120", esito: "Autorizzazione negata" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_121",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 121", esito: "Autorizzazione negata" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_122",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 122", esito: "Autorizzazione negata" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_123",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 123", esito: "Autorizzazione negata" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_124",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 124", esito: "Autorizzazione negata" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_125",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 125", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_126",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 126", esito: "Autorizzazione negata" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_129",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 129", esito: "Autorizzazione negata" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_200",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 200", esito: "Autorizzazione negata" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_202",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 202", esito: "Autorizzazione negata" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_204",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 204", esito: "Autorizzazione negata" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_208",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 208", esito: "I dati del metodo di pagamento non sono corretti" }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_209",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 209", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_210",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 210", esito: "I dati del metodo di pagamento non sono corretti" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_413",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 413", esito: "Autorizzazione negata" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_888",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 888", esito: "Autorizzazione negata" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_902",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 902", esito: "Autorizzazione negata" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_903",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 903", esito: "Autorizzazione negata" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_904",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 904", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_906",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 906", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_907",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 907", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_908",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 908", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_909",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 909", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_911",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 911", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_913",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 913", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_999",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 999", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_GENERIC",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND GENERIC ERROR CODE", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_CLOSURE_REQUESTED_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_NOT_RECEIVED",
      { title: "EXPIRED STATUS FOR CLOSURE_REQUESTED TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT NOT_RECEIVED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_CLOSURE_ERROR_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_NOT_RECEIVED",
      { title: "EXPIRED STATUS FOR CLOSURE_ERROR TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT NOT_RECEIVED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_NOTIFICATION_REQUESTED_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_OK",
      { title: "EXPIRED STATUS FOR NOTIFICATION_REQUESTED TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT OK", esito: "Hai pagato" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_NOTIFICATION_ERROR_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_OK",
      { title: "EXPIRED STATUS FOR NOTIFICATION_ERROR TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT OK", esito: "Hai pagato" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_NOTIFICATION_REQUESTED_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_KO",
      { title: "EXPIRED STATUS FOR NOTIFICATION_REQUESTED TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT KO", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_NOTIFICATION_ERROR_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_KO",
      { title: "EXPIRED STATUS FOR NOTIFICATION_ERROR TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT KO", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "REFUND_REQUESTED_TRANSACTION_WITH_NPG_AUTH_STATUS_EXECUTED",
      { title: "REFUND_REQUESTED STATUS FOR TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "REFUND_ERROR_TRANSACTION_WITH_NPG_AUTH_STATUS_EXECUTED",
      { title: "REFUND_ERROR STATUS FOR TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED", esito: "Si è verificato un errore imprevisto" }
    ],
    [
      "REFUNDED_TRANSACTION_WITH_NPG_AUTH_STATUS_EXECUTED",
      { title: "REFUNDED STATUS FOR TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED", esito: "Si è verificato un errore imprevisto" }
    ]

  ]);


  /**
   * Increase default test timeout (80000ms)
   * to support entire payment flow
    */
  jest.setTimeout(120000);
  jest.retryTimes(0);
  page.setDefaultNavigationTimeout(120000);
  page.setDefaultTimeout(120000);

  beforeAll(async () => {
    await page.goto(CHECKOUT_OUTCOME_URL);
    await page.setViewport({ width: 1200, height: 907 });
    //await acceptCookiePolicy();
  })


  Array.from(mockFlowWithExpectedResultMap.keys()).forEach(keyFlowId => {
    it(mockFlowWithExpectedResultMap.get(keyFlowId)?.title || "", async () => {
      await page.evaluate(() => {
        //set item into sessionStorage and localStorage for pass the route Guard
        let sessionData = '{"authToken":"token","clientId":"CHECKOUT","payments":[{"amount":12000,"isAllCCP":false,"paymentToken":"paymentToken1","reason":"reason1","rptId":"77777777777302001751670642100","transferList":[{"digitalStamp":true,"paFiscalCode":"66666666666","transferAmount":100,"transferCategory":"transferCategory1"},{"digitalStamp":false,"paFiscalCode":"77777777777","transferAmount":900,"transferCategory":"transferCategory2"}]}],"status":"ACTIVATED","transactionId":"f4f1b6a82b7d473583b506fcd5edf308"}';
        sessionStorage.setItem('transaction', sessionData);
        localStorage.setItem('transaction', sessionData);
        localStorage.setItem("i18nextLng", "it");
      });
      
      await page.setCookie({ name: "mockFlow", value: keyFlowId });
      await page.goto(CHECKOUT_OUTCOME_URL);
      const resultTitleSelector = "#responsePageMessageTitle";
      const message = await page.waitForSelector(resultTitleSelector);
      const responseMessage = await message.evaluate((el) => el.textContent);
      expect(responseMessage).toContain(mockFlowWithExpectedResultMap.get(keyFlowId)?.esito);
    })
  });

});