import itTranslation from "../translations/it/translations.json";
import deTranslation from "../translations/de/translations.json";
import enTranslation from "../translations/en/translations.json";
import frTranslation from "../translations/fr/translations.json";
import slTranslation from "../translations/sl/translations.json";

describe.each([
  ["it", itTranslation],
  ["en", enTranslation],
  ["fr", frTranslation],
  ["de", deTranslation],
  ["sl", slTranslation]
])("Unauthorized npg final status mapping tests for [%s] language", (lang, translation) => {

  /**
     * Test input and configuration
  */

  const CHECKOUT_OUTCOME_URL = "http://localhost:1234/esito";

  /**
   * Add all mock flow. Reference to the flow defined into the checkout be mock
   */

  const mockFlowWithExpectedResultMap = new Map([
    [
      "AUTHORIZATION_REQUESTED_NO_NPG_OUTCOME",
      { title: "AUTHORIZATION REQUESTED WITH NO NPG OUTCOME", esito: translation.paymentResponsePage[17].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_EXECUTED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS EXECUTED", esito: translation.paymentResponsePage[1].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_AUTHORIZED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS AUTHORIZED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_PENDING",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS PENDING", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_VOIDED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS VOIDED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_REFUNDED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUSREFUNDED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_FAILED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS FAILED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_CANCELED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS CANCELED", esito: translation.paymentResponsePage[8].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DENIED_BY_RISK",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DENIED_BY_RISK", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_THREEDS_VALIDATED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS THREEDS_VALIDATED", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_THREEDS_FAILED",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS THREEDS_FAILED", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_100",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 100", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_101",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 101", esito: translation.paymentResponsePage[7].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_102",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 102", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_104",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 104", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_106",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 106", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_109",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 109", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_110",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 110", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_111",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 111", esito: translation.paymentResponsePage[7].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_115",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 115", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_116",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 116", esito: translation.paymentResponsePage[116].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_117",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 117", esito: translation.paymentResponsePage[117].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_118",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 118", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_119",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 119", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_120",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 120", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_121",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 121", esito: translation.paymentResponsePage[121].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_122",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 122", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_123",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 123", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_124",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 124", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_125",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 125", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_126",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 126", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_129",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 129", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_200",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 200", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_202",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 202", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_204",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 204", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_208",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 208", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_209",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 209", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_210",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 210", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_413",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 413", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_888",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 888", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_902",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 902", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_903",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 903", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_904",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 904", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_906",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 906", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_907",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 907", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_908",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 908", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_909",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 909", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_911",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 911", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_913",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 913", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_999",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 999", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "AUTHORIZATION_COMPLETED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_GENERIC",
      { title: "AUTHORIZATION COMPLETED WITH NPG AUTHORIZATION STATUS DECLINED AND GENERIC ERROR CODE", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_EXECUTED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS EXECUTED", esito: translation.paymentResponsePage[17].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_AUTHORIZED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS AUTHORIZED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_PENDING",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS PENDING", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_VOIDED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS VOIDED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_REFUNDED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUSREFUNDED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_FAILED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS FAILED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_CANCELED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS CANCELED", esito: translation.paymentResponsePage[8].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DENIED_BY_RISK",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DENIED_BY_RISK", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_THREEDS_VALIDATED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS THREEDS_VALIDATED", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_THREEDS_FAILED",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS THREEDS_FAILED", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_100",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 100", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_101",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 101", esito: translation.paymentResponsePage[7].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_102",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 102", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_104",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 104", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_106",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 106", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_109",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 109", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_110",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 110", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_111",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 111", esito: translation.paymentResponsePage[7].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_115",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 115", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_116",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 116", esito: translation.paymentResponsePage[116].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_117",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 117", esito: translation.paymentResponsePage[117].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_118",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 118", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_119",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 119", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_120",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 120", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_121",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 121", esito: translation.paymentResponsePage[121].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_122",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 122", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_123",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 123", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_124",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 124", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_125",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 125", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_126",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 126", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_129",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 129", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_200",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 200", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_202",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 202", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_204",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 204", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_208",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 208", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_209",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 209", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_210",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 210", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_413",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 413", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_888",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 888", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_902",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 902", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_903",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 903", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_904",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 904", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_906",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 906", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_907",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 907", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_908",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 908", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_909",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 909", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_911",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 911", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_913",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 913", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_999",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 999", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_REQUESTED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_GENERIC",
      { title: "CLOSURE REQUESTED WITH NPG AUTHORIZATION STATUS DECLINED AND GENERIC ERROR CODE", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_EXECUTED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS EXECUTED", esito: translation.paymentResponsePage[1].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_AUTHORIZED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS AUTHORIZED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_PENDING",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS PENDING", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_VOIDED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS VOIDED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_REFUNDED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUSREFUNDED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_FAILED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS FAILED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_CANCELED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS CANCELED", esito: translation.paymentResponsePage[8].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DENIED_BY_RISK",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DENIED_BY_RISK", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_THREEDS_VALIDATED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS THREEDS_VALIDATED", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_THREEDS_FAILED",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS THREEDS_FAILED", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_100",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 100", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_101",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 101", esito: translation.paymentResponsePage[7].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_102",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 102", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_104",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 104", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_106",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 106", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_109",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 109", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_110",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 110", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_111",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 111", esito: translation.paymentResponsePage[7].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_115",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 115", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_116",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 116", esito: translation.paymentResponsePage[116].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_117",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 117", esito: translation.paymentResponsePage[117].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_118",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 118", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_119",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 119", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_120",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 120", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_121",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 121", esito: translation.paymentResponsePage[121].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_122",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 122", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_123",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 123", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_124",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 124", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_125",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 125", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_126",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 126", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_129",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 129", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_200",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 200", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_202",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 202", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_204",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 204", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_208",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 208", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_209",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 209", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_210",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 210", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_413",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 413", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_888",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 888", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_902",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 902", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_903",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 903", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_904",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 904", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_906",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 906", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_907",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 907", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_908",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 908", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_909",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 909", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_911",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 911", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_913",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 913", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_999",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 999", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_GENERIC",
      { title: "CLOSURE ERROR WITH NPG AUTHORIZATION STATUS DECLINED AND GENERIC ERROR CODE", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_ON_CLOSE_PAYMENT_ERROR_CODE_422_DID_NOT_RECEIVE_RPT",
      { title: "CLOSURE ERROR WITH NPG ON CLOSE PAYMENT ERROR CODE 422 DID NOT RECEIVE RPT", esito: translation.paymentResponsePage[18].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_ON_CLOSE_PAYMENT_ERROR_CODE_422_OUTCOME_ALREADY_ACQUIRED",
      { title: "CLOSURE ERROR WITH NPG ON CLOSE PAYMENT ERROR CODE 422 OUTCOME ALREADY ACQUIRED", esito: translation.paymentResponsePage[1].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_ON_CLOSE_PAYMENT_ERROR_CODE_400_REFUND_CASES",
      { title: "CLOSURE ERROR WITH NPG ON CLOSE PAYMENT ERROR CODE 400 REFUND CASES", esito: translation.paymentResponsePage[18].title }
    ],
    [
      "CLOSURE_ERROR_WITH_NPG_ON_CLOSE_PAYMENT_ERROR_CODE_404_REFUND_CASES",
      { title: "CLOSURE ERROR WITH NPG ON CLOSE PAYMENT ERROR CODE 404 REFUND CASES", esito: translation.paymentResponsePage[18].title }
    ],
    [
      "CLOSED_WITH_NPG_AUTH_STATUS_EXECUTED_SEND_PAYMENT_RESULT_NOT_RECEIVED",
      { title: "CLOSED WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT NOT_RECEIVED", esito: translation.paymentResponsePage[17].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_AUTHORIZED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS AUTHORIZED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_PENDING",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS PENDING", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_VOIDED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS VOIDED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_REFUNDED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUSREFUNDED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_FAILED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS FAILED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_CANCELED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS CANCELED", esito: translation.paymentResponsePage[8].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DENIED_BY_RISK",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DENIED_BY_RISK", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_THREEDS_VALIDATED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS THREEDS_VALIDATED", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_THREEDS_FAILED",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS THREEDS_FAILED", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_100",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 100", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_101",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 101", esito: translation.paymentResponsePage[7].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_102",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 102", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_104",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 104", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_106",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 106", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_109",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 109", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_110",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 110", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_111",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 111", esito: translation.paymentResponsePage[7].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_115",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 115", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_116",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 116", esito: translation.paymentResponsePage[116].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_117",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 117", esito: translation.paymentResponsePage[117].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_118",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 118", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_119",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 119", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_120",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 120", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_121",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 121", esito: translation.paymentResponsePage[121].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_122",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 122", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_123",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 123", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_124",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 124", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_125",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 125", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_126",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 126", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_129",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 129", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_200",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 200", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_202",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 202", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_204",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 204", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_208",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 208", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_209",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 209", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_210",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 210", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_413",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 413", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_888",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 888", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_902",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 902", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_903",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 903", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_904",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 904", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_906",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 906", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_907",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 907", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_908",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 908", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_909",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 909", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_911",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 911", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_913",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 913", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_999",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 999", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "UNAUTHORIZED_WITH_NPG_AUTH_STATUS_DECLINED_ERROR_CODE_GENERIC",
      { title: "UNAUTHORIZED WITH NPG AUTHORIZATION STATUS DECLINED AND GENERIC ERROR CODE", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "NOTIFICATION_REQUESTED_WITH_NPG_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_OK",
      { title: "NOTIFICATION REQUESTED WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT OK", esito: translation.paymentResponsePage[0].title.replace("{{amount}}", "0,00\xa0€") }
    ],
    [
      "NOTIFICATION_REQUESTED_WITH_NPG_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_KO",
      { title: "NOTIFICATION REQUESTED WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT KO", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "NOTIFICATION_ERROR_WITH_NPG_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_OK",
      { title: "NOTIFICATION ERROR WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT OK", esito: translation.paymentResponsePage[0].title.replace("{{amount}}", "0,00\xa0€") }
    ],
    [
      "NOTIFICATION_ERROR_WITH_NPG_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_KO",
      { title: "NOTIFICATION ERROR WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT KO", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "NOTIFIED_OK_WITH_NPG_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_OK",
      { title: "NOTIFIED OK WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT OK", esito: translation.paymentResponsePage[0].title.replace("{{amount}}", "0,00\xa0€") }
    ],
    [
      "NOTIFIED_KO_WITH_NPG_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_KO",
      { title: "NOTIFIED KO ERROR WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT KO", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_REQUESTED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION_REQUESTED TRANSACTION", esito: translation.paymentResponsePage[17].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_EXECUTED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED", esito: translation.paymentResponsePage[1].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_AUTHORIZED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS AUTHORIZED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_PENDING",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS PENDING", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_VOIDED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS VOIDED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_REFUNDED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUSREFUNDED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_FAILED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS FAILED", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_CANCELED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS CANCELED", esito: translation.paymentResponsePage[8].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DENIED_BY_RISK",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DENIED_BY_RISK", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_THREEDS_VALIDATED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS THREEDS_VALIDATED", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_THREEDS_FAILED",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS THREEDS_FAILED", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_100",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 100", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_101",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 101", esito: translation.paymentResponsePage[7].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_102",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 102", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_104",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 104", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_106",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 106", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_109",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 109", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_110",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 110", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_111",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 111", esito: translation.paymentResponsePage[7].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_115",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 115", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_116",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 116", esito: translation.paymentResponsePage[116].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_117",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 117", esito: translation.paymentResponsePage[117].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_118",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 118", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_119",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 119", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_120",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 120", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_121",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 121", esito: translation.paymentResponsePage[121].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_122",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 122", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_123",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 123", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_124",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 124", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_125",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 125", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_126",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 126", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_129",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 129", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_200",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 200", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_202",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 202", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_204",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 204", esito: translation.paymentResponsePage[2].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_208",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 208", esito: translation.paymentResponsePage[3].title }
    ],

    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_209",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 209", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_210",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 210", esito: translation.paymentResponsePage[3].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_413",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 413", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_888",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 888", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_902",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 902", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_903",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 903", esito: translation.paymentResponsePage[2].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_904",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 904", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_906",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 906", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_907",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 907", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_908",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 908", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_909",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 909", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_911",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 911", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_913",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 913", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_999",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND ERROR CODE 999", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_AUTHORIZATION_COMPLETED_AUTH_STATUS_DECLINED_ERROR_CODE_GENERIC",
      { title: "EXPIRED STATUS FOR AUTHORIZATION COMPLETED TRANSACTION WITH NPG AUTHORIZATION STATUS DECLINED AND GENERIC ERROR CODE", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_CLOSURE_REQUESTED_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_NOT_RECEIVED",
      { title: "EXPIRED STATUS FOR CLOSURE_REQUESTED TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT NOT_RECEIVED", esito: translation.paymentResponsePage[17].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_CLOSURE_ERROR_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_NOT_RECEIVED",
      { title: "EXPIRED STATUS FOR CLOSURE_ERROR TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT NOT_RECEIVED", esito: translation.paymentResponsePage[17].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_NOTIFICATION_REQUESTED_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_OK",
      { title: "EXPIRED STATUS FOR NOTIFICATION_REQUESTED TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT OK", esito: translation.paymentResponsePage[0].title.replace("{{amount}}", "0,00\xa0€") }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_NOTIFICATION_ERROR_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_OK",
      { title: "EXPIRED STATUS FOR NOTIFICATION_ERROR TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT OK", esito: translation.paymentResponsePage[0].title.replace("{{amount}}", "0,00\xa0€") }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_NOTIFICATION_REQUESTED_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_KO",
      { title: "EXPIRED STATUS FOR NOTIFICATION_REQUESTED TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT KO", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "EXPIRED_TRANSACTION_FOR_NOTIFICATION_ERROR_AUTH_STATUS_EXECUTED_AND_SEND_PAYMENT_RESULT_KO",
      { title: "EXPIRED STATUS FOR NOTIFICATION_ERROR TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED AND SEND PAYMENT RESULT KO", esito: translation.paymentResponsePage[25].title }
    ],
    [
      "REFUND_REQUESTED_TRANSACTION_WITH_NPG_AUTH_STATUS_EXECUTED",
      { title: "REFUND_REQUESTED STATUS FOR TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED", esito: translation.paymentResponsePage[1].title }
    ],
    [
      "REFUND_ERROR_TRANSACTION_WITH_NPG_AUTH_STATUS_EXECUTED",
      { title: "REFUND_ERROR STATUS FOR TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED", esito: translation.paymentResponsePage[1].title }
    ],
    [
      "REFUNDED_TRANSACTION_WITH_NPG_AUTH_STATUS_EXECUTED",
      { title: "REFUNDED STATUS FOR TRANSACTION WITH NPG AUTHORIZATION STATUS EXECUTED", esito: translation.paymentResponsePage[25].title }
    ]

  ]);


  /**
   * Increase default test timeout (80000ms)
   * to support entire payment flow
    */
  jest.setTimeout(30000);
  jest.retryTimes(0);
  page.setDefaultNavigationTimeout(10000);
  page.setDefaultTimeout(10000);

  beforeAll(async () => {
    await page.goto(CHECKOUT_OUTCOME_URL);
    await page.setViewport({ width: 1200, height: 907 });
    //await acceptCookiePolicy();
  })


  Array.from(mockFlowWithExpectedResultMap.keys()).forEach(keyFlowId => {
    it(mockFlowWithExpectedResultMap.get(keyFlowId)?.title || "", async () => {
      await page.evaluate((language) => {
        //set item into sessionStorage and localStorage for pass the route Guard
        let sessionData = '{"authToken":"token","clientId":"CHECKOUT","payments":[{"amount":12000,"isAllCCP":false,"paymentToken":"paymentToken1","reason":"reason1","rptId":"77777777777302001751670642100","transferList":[{"digitalStamp":true,"paFiscalCode":"66666666666","transferAmount":100,"transferCategory":"transferCategory1"},{"digitalStamp":false,"paFiscalCode":"77777777777","transferAmount":900,"transferCategory":"transferCategory2"}]}],"status":"ACTIVATED","transactionId":"f4f1b6a82b7d473583b506fcd5edf308"}';
        sessionStorage.setItem('transaction', sessionData);
        localStorage.setItem('transaction', sessionData);
        localStorage.setItem("i18nextLng", language);
      }, lang);
      
      await page.setCookie({ name: "mockFlow", value: keyFlowId });
      await page.goto(CHECKOUT_OUTCOME_URL);
      const resultTitleSelector = "#responsePageMessageTitle";
      const message = await page.waitForSelector(resultTitleSelector);
      const responseMessage = await message.evaluate((el) => el.textContent);
      expect(responseMessage).toContain(mockFlowWithExpectedResultMap.get(keyFlowId)?.esito);
    })
  });

});