name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                package-manager: yarn
                test-script: yarn test
                coverage-file: ./coverage/checkout-unit-TEST.xml
                base-coverage-file: ./coverage/master/checkout-unit-TEST.xml