name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                package-manager: yarn
                test-script: yarn test:coverage
                output: report-markdown
            - uses: marocchino/sticky-pull-request-comment@v2
              with:
                  # pass output from the previous step by id.
                  message: ${{ steps.coverage.outputs.report }}